#!/usr/bin/env bash
set -euo pipefail

mkdir -p .ci

mise run ci:update-mods > .ci/update_log.txt

cat .ci/update_log.txt

echo "This PR was auto-generated by \`Pakku\` update task." > .ci/pr_body.md
echo "" >> .ci/pr_body.md
echo "### Pakku Update Log" >> .ci/pr_body.md
echo '```text' >> .ci/pr_body.md

sed 's/\x1b\[[0-9;]*m//g' .ci/update_log.txt >> .ci/pr_body.md

echo '```' >> .ci/pr_body.md