[tools]
java = "temurin-25"
jq = "latest"
go = "latest"
"go:github.com/itzg/mc-monitor" = "latest"
act = "latest"

[hooks]
postinstall = { task = "pakku:update" }

[shell_alias]
pakku = "java --enable-native-access=ALL-UNNAMED -jar .mise/pakku.jar"

