name = "CloverCraft Season 4"
author = "CloverCraft Team, Syfe, Colonel"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "760a339ae4c2f95c8e53ec728bca47084d0c3b391e5d3d824f4d38a0125d170a"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
unsup = "1.2.7"

[options]
acceptable-game-versions = ["26.1"]
