name = "CloverCraft Season 4"
author = "CloverCraft Team, Syfe, Colonel"
version = "@modpack_version@"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4148d877dcd68e5188cc41eac81eda2b51d4754e412a9a95fda8b0a69e29486b"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
unsup = "1.2.7"

[options]
acceptable-game-versions = ["26.1"]
