name = "CloverCraft Season 4"
author = "CloverCraft Team, Syfe, Colonel"
version = "@modpack_version@"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e3931a6f78af4f527f0b294bd9506d130c408ce66c2130df2cd0438139c89648"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
unsup = "1.2.7"

[options]
acceptable-game-versions = ["26.1"]
