version=1
preset=minecraft

source_format=packwiz
source=http://localhost:8080/pack.toml

offer_change_flavors=true

[branding]
modpack_name=CloverCraft

# TODO: remove, hardcoding this for now until we make the repo public
# this is obviously a security risk but it's a fine grained access token for the season 4 repo that only has content read, so it should be fine
[authorization]
https://raw.githubusercontent.com=Bearer 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