# ===========
#  FLAVOURS
# ===========

# ===================
# Performance Profile
# ===================

[flavor_groups.profile]
name = "Graphics and Effects"
description = "Choose the profile that best matches your computer's specs."
side = "client"
choices = [
    { id = "ultra", name = "Ultra", description = "For high-end PCs. Shader support, advanced physics, and all visual effects." },
    { id = "standard", name = "Standard", description = "Balanced performance and visuals. Includes shader support and QoL enhancements." },
    { id = "lite", name = "Lite", description = "Maximum performance for low-end laptops and older PCs. Disables shaders, LOD renderers, heavy particles, and ambient physics." }
]

# ===================
#        LOD
# ===================

[flavor_groups.lod]
name = "Distant Rendering (LODs)"
description = "Render chunks extremely far away. Highly performance-intensive!"
side = "client"
choices = [
    { id = "none", name = "None", description = "Standard Minecraft render distance. Best for performance and stability." },
    { id = "voxy", name = "Voxy", description = "An advanced, highly performant voxel-based LOD renderer. Great for vanilla-like rendering, but experimental." },
    { id = "dh", name = "Distant Horizons", description = "The classic LOD renderer." }
]

# ===========
#    MAPS
# ===========

[metafile]
# =================
#      ULTRA
# =================
inventory-particles = { flavors = ["ultra"] }
smooth-scroll = { flavors = ["ultra"] }
nuit = { flavors = ["ultra"] }
blur-plus = { flavors = ["ultra"] }
elytra-physics = { flavors = ["ultra"] }
better-smoke = { flavors = ["ultra"] }
elytra-contrails-mod = { flavors = ["ultra"] }

# =================
#     STANDARD
# =================
particular-reforged = { flavors = ["ultra", "standard"] }
visuality = { flavors = ["ultra", "standard"] }
subtle-effects = { flavors = ["ultra", "standard"] }
sound-physics-remastered = { flavors = ["ultra", "standard"] }
respackopts = { flavors = ["ultra", "standard"] }
particle-effects = { flavors = ["ultra", "standard"] }
fallingleaves = { flavors = ["ultra", "standard"] }
iris = { flavors = ["ultra", "standard"] }
build-guide = { flavors = ["ultra", "standard"] }
animaticarefabricated = { flavors = ["ultra", "standard"] }
cit-resewn-continuation = { flavors = ["ultra", "standard"] }
ears = { flavors = ["ultra", "standard"] }

# =================
#       LITE
# =================
coolrain = { flavors = ["ultra", "standard", "lite"] }

# =================
#      VOXY
# =================
voxy = { flavors = ["voxy"] }
voxy-extra = { flavors = ["voxy"] }

# =================
#       DH
# =================
distanthorizons = { flavors = ["dh"] }