["ci:run"]
    description= "Runs the full pipeline in one shot"
    run = [
        { task = "build:export" },
        { task = "server:stage", args = ["--wipe"] },
        { task = "server:test" }
    ]