gamerule.minecraft:keep_inventory=true
gamerule.minecraft:player_sleeping_percentage=20
gamerule.mob_explosion_griefing:enderman_griefing=false
gamerule.mob_explosion_griefing:creeper_griefing=false
gamerule.mob_explosion_griefing:door_breaking_griefing=false