name: Automated Mod Updates

on:
  schedule:
    - cron: '0 0 */3 * *'
  workflow_dispatch: 

permissions:
  contents: write
  pull-requests: write

jobs:
  update-mods:
    name: Check for Mod Updates
    runs-on: ubuntu-latest
    steps:
      - name: Generate Bot Token
        uses: actions/create-github-app-token@v3
        id: app-token
        with:
          client-id: ${{ vars.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - id: committer
        run: echo "string=${{ steps.app-token.outputs.app-slug }}[bot] <${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com>"  >> "$GITHUB_OUTPUT"

      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Setup Environment (Mise)
        uses: jdx/mise-action@v4

      - name: Run Packwiz Update & Generate Log
        run: mise run ci:generate-pr

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ steps.app-token.outputs.token }}
          author: ${{ steps.committer.outputs.string }}
          committer: ${{ steps.committer.outputs.string }}
          commit-message: "chore(mods): update mod versions via packwiz"
          title: "Automated Mod Updates"
          body-path: .ci/pr_body.md
          branch: "auto-update-mods"
          base: "main"
          labels: "dependencies"
          delete-branch: true